"""Create DOM-SEG tables for Segurança da Informação domain.

Revision ID: 20260901_04
Revises: 20260901_03
Create Date: 2026-09-01

Tarefa: Create SQLAlchemy model tables for DOM-SEG domain:
- seg.controles_seguranca
- seg.politicas_seguranca
- seg.incidentes_seguranca
- seg.chaves_criptograficas
- seg.credenciais

This migration creates the infrastructure tables for the Segurança da Informação
domain as implemented in the SIGMUN system.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "20260901_04"
down_revision = "20260901_03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controles_seguranca",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("categoria", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("nivel_risco", sa.Text(), nullable=False),
        sa.Column("responsavel_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo", name="uq_controles_codigo"),
    )
    op.create_table(
        "politicas_seguranca",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("titulo", sa.Text(), nullable=False),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.Column("versao", sa.Text(), nullable=False),
        sa.Column("aprovador_id", sa.Text(), nullable=True),
        sa.Column("data_aprovacao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_revisao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ativa", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo", name="uq_politicas_codigo"),
    )
    op.create_table(
        "incidentes_seguranca",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("titulo", sa.Text(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("severidade", sa.Text(), nullable=False),
        sa.Column("impacto", sa.Text(), nullable=True),
        sa.Column("categoria", sa.Text(), nullable=True),
        sa.Column("relator_id", sa.Text(), nullable=True),
        sa.Column("atribuido_a", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_resolucao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("titulo", name="uq_incidentes_titulo"),
    )
    op.create_table(
        "chaves_criptograficas",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("algoritmo", sa.Text(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("tamanho_bits", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("data_expiracao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responsavel_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome", name="uq_chaves_nome"),
    )
    op.create_table(
        "credenciais",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("usuario_id", sa.Text(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("identificador", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("validade", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_uso", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tentativas_falhas", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identificador", name="uq_credenciais_identificador"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credenciais", schema="seg")
    op.drop_table("chaves_criptograficas", schema="seg")
    op.drop_table("incidentes_seguranca", schema="seg")
    op.drop_table("politicas_seguranca", schema="seg")
    op.drop_table("controles_seguranca", schema="seg")
    # ### end Alembic commands ###