"""Eventos de domínio do módulo de Identidade e Acesso (re-exports)."""

from src.modules.sigmun_idn.domain.events.usuario_events import (
    DomainEvent,
    EventoIdentidade,
    LoginFalhouEvent,
    LoginRealizadoEvent,
    LogoutRealizadoEvent,
    PermissaoConcedidaEvent,
    PermissaoCriadaEvent,
    PermissaoRevogadaEvent,
    RoleAtualizadaEvent,
    RoleCriadaEvent,
    RoleRemovidaEvent,
    SenhaAlteradaEvent,
    SessaoCriadaEvent,
    SessaoInvalidadaEvent,
    UsuarioAtivadoEvent,
    UsuarioBloqueadoEvent,
    UsuarioCriadoEvent,
    UsuarioDesativadoEvent,
)

__all__ = [
    "EventoIdentidade",
    "DomainEvent",
    "UsuarioCriadoEvent",
    "UsuarioAtivadoEvent",
    "UsuarioDesativadoEvent",
    "UsuarioBloqueadoEvent",
    "LoginRealizadoEvent",
    "LoginFalhouEvent",
    "LogoutRealizadoEvent",
    "PermissaoConcedidaEvent",
    "PermissaoRevogadaEvent",
    "RoleCriadaEvent",
    "RoleAtualizadaEvent",
    "RoleRemovidaEvent",
    "PermissaoCriadaEvent",
    "SenhaAlteradaEvent",
    "SessaoCriadaEvent",
    "SessaoInvalidadaEvent",
]
